# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160121_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to='%Y/%m/%d'),
        ),
    ]
